import sqlite3

# Connect to SQLite database (creates a new database if it doesn't exist)
conn = sqlite3.connect('workout.db')

# Create a cursor object to execute SQL commands
cursor = conn.cursor()

# Create the Exercises table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS Exercises (
        name TEXT,
        type TEXT,
        area TEXT,
        level TEXT,
        link TEXT
    )
''')

# Insert some sample data
exercises = [
    ('Push-up', 'Bodyweight', 'Chest/Triceps', 'Beginner', 'Info: https://musclewiki.com/'),
    ('Pull-up', 'Bodyweight', 'Back/Biceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Squat', 'Bodyweight', 'Legs', 'Beginner', 'Info: https://musclewiki.com/'),
    ('Plank', 'Bodyweight', 'Core', 'Beginner', 'Info: https://musclewiki.com/'),
    ('Crunches', 'Bodyweight', 'Core', 'Beginner', 'Info: https://musclewiki.com/'),
    ('Lunges', 'Bodyweight', 'Full Body', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Plank with Shoulder Taps', 'Bodyweight', 'Full Body', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Plank', 'Bodyweight', 'Full Body', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Jump Squats', 'Bodyweight', 'Full Body', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Russian Twists', 'Bodyweight', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Jump Squats', 'Bodyweight', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Crunches', 'Bodyweight', 'Core', 'Beginner', 'Info: https://musclewiki.com/'),
    ('Mountain Climbers', 'Bodyweight', 'Full Body', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Leg Raises', 'Bodyweight', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Dips', 'Bodyweight', 'Triceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Bicycle Crunches', 'Bodyweight', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Wall Sit', 'Bodyweight', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Box Jumps', 'Bodyweight', 'Legs', 'Advanced', 'Info: https://musclewiki.com/'),
    ('Superman', 'Bodyweight', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Tricep Dips', 'Bodyweight', 'Triceps', 'Beginner', 'Info: https://musclewiki.com/'),
    ('Step-ups', 'Bodyweight', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Russian Push-ups', 'Bodyweight', 'Chest/Triceps', 'Advanced', 'Info: https://musclewiki.com/'),
    ('Diamond Push-ups', 'Bodyweight', 'Triceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Single-leg Deadlifts', 'Bodyweight', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Flutter Kicks', 'Bodyweight', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Pike Push-ups', 'Bodyweight', 'Shoulders', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Jump Rope', 'Bodyweight', 'Cardio', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Push-up to Side Plank', 'Bodyweight', 'Chest/Triceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Reverse Crunches', 'Bodyweight', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Walking Lunges', 'Bodyweight', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Inchworms', 'Bodyweight', 'Full Body', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Side Plank', 'Bodyweight', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Handstand Push-ups', 'Bodyweight', 'Shoulders', 'Advanced', 'Info: https://musclewiki.com/'),
    ('Jumping Lunges', 'Bodyweight', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Push-up and Rotation', 'Bodyweight', 'Chest/Triceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Single-leg Glute Bridge', 'Bodyweight', 'Glutes', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Spiderman Push-ups', 'Bodyweight', 'Chest/Triceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Scissor Kicks', 'Bodyweight', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Bear Crawls', 'Bodyweight', 'Full Body', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Knee-to-Elbow Plank', 'Bodyweight', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Chair Dips', 'Bodyweight', 'Triceps', 'Beginner', 'Info: https://musclewiki.com/'),
    ('Leg Pull-ins', 'Bodyweight', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Hand Release Push-ups', 'Bodyweight', 'Chest/Triceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Split Squats', 'Bodyweight', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Bodyweight Rows', 'Bodyweight', 'Back/Biceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Cross-body Mountain Climbers', 'Bodyweight', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Dolphin Plank', 'Bodyweight', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Tricep Push-ups', 'Bodyweight', 'Triceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Bench Press', 'Equipment', 'Chest', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Deadlift', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Barbell Squat', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Barbell Row', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Leg Press', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Lat Pulldown', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Cable Flyes', 'Equipment', 'Chest', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Leg Extension', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Seated Row', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Shoulder Press', 'Equipment', 'Shoulders', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Chest Press Machine', 'Equipment', 'Chest', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Lateral Raise', 'Equipment', 'Shoulders', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Leg Curl', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Pull-up Machine', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Hack Squat', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Tricep Pushdown', 'Equipment', 'Triceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Cable Rows', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Romanian Deadlift', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Hammer Curls', 'Equipment', 'Biceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Leg Press Machine', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Chest Fly Machine', 'Equipment', 'Chest', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Calf Raise', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Barbell Curl', 'Equipment', 'Biceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Cable Crunches', 'Equipment', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Cable Lateral Raise', 'Equipment', 'Shoulders', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Leg Press Calf Raise', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Cable Bicep Curl', 'Equipment', 'Biceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Incline Bench Press', 'Equipment', 'Chest', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('T-Bar Row', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Preacher Curls', 'Equipment', 'Biceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Cable Rope Tricep Pushdown', 'Equipment', 'Triceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Lying Leg Curl', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Lat Pulldown Machine', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Chest Supported Row', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Hamstring Curl Machine', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Assisted Pull-up Machine', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Dumbbell Flyes', 'Equipment', 'Chest', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Seated Leg Press', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Cable Face Pulls', 'Equipment', 'Shoulders', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Machine Shoulder Press', 'Equipment', 'Shoulders', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Cable Tricep Kickbacks', 'Equipment', 'Triceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Smith Machine Squat', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Rows', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Chest Press', 'Equipment', 'Chest', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Squats', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Bicep Curls', 'Equipment', 'Biceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Tricep Extensions', 'Equipment', 'Triceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Pike', 'Equipment', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Mountain Climbers', 'Equipment', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Hamstring Curl', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Lateral Lunges', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Plank', 'Equipment', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Reverse Flyes', 'Equipment', 'Shoulders', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Pistol Squat', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Y Deltoid Flyes', 'Equipment', 'Shoulders', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Single Leg Squat', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Atomic Push-up', 'Equipment', 'Chest', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Body Saw', 'Equipment', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Jump Squat', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Chest Flyes', 'Equipment', 'Chest', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Hip Press', 'Equipment', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Lunge', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX T Deltoid Flyes', 'Equipment', 'Shoulders', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Tricep Press', 'Equipment', 'Triceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Power Pull', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Push-up', 'Equipment', 'Chest', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Spiderman Push-up', 'Equipment', 'Chest', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Clock Press', 'Equipment', 'Chest', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Reverse Lunge', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Pike Push-up', 'Equipment', 'Shoulders', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Sprinter Start', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Suspended Crunch', 'Equipment', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX High Row', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX I Y T', 'Equipment', 'Shoulders', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Plank with Alternating Knee Tuck', 'Equipment', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Sprinter Lunge', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Front Squat', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Side Plank', 'Equipment', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Cossack Squat', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Low Row', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Mountain Climber with Twist', 'Equipment', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Push-up with Pike', 'Equipment', 'Chest', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Hamstring Runner', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Atomic Pike', 'Equipment', 'Core', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Single Leg Deadlift', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Y Flyes', 'Equipment', 'Shoulders', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Glute Bridge', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Dumbbell Bench Press', 'Equipment', 'Chest', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Dumbbell Row', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Dumbbell Lunges', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Dumbbell Shoulder Press', 'Equipment', 'Shoulders', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Dumbbell Bicep Curl', 'Equipment', 'Biceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Dumbbell Tricep Extension', 'Equipment', 'Triceps', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Dumbbell Squats', 'Equipment', 'Legs', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Dumbbell Side Lateral Raise', 'Equipment', 'Shoulders', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Dumbbell Deadlifts', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Dumbbell Thrusters', 'Equipment', 'Full Body', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Kettlebell Swings', 'Equipment', 'Full Body', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('TRX Squat Jumps', 'Equipment', 'Full Body', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Military Press', 'Equipment', 'Shoulders', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Bent Over Rows', 'Equipment', 'Back', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Barbell Deadlift', 'Equipment', 'Full Body', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Dumbbell Step-ups', 'Equipment', 'Full Body', 'Intermediate', 'Info: https://musclewiki.com/'),
    ('Burpees', 'Bodyweight', 'Full Body', 'Intermediate', 'Info: https://musclewiki.com/'),
]

cursor.executemany('''
    INSERT INTO Exercises (name, type, area, level, link)
    VALUES (?, ?, ?, ?, ?)
''', exercises)

# Commit the transaction to save changes
conn.commit()

# Query the database
cursor.execute('SELECT * FROM Exercises')
exercises = cursor.fetchall()

for exercise in exercises:
    print(exercise)

# Close the connection
conn.close()